#!/bin/sh

# Set these paths appropriately

BIN=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/bin
CMD=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/cmd
LIB=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/bulgarian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
