#!/bin/sh

# Set these paths appropriately

BIN=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/bin
CMD=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/cmd
LIB=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par
LEXFILE=${LIB}/english-lexicon.txt

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
