#!/bin/sh

# Set these paths appropriately

BIN=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/bin
CMD=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/cmd
LIB=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
