#!/bin/sh

# Set these paths appropriately

BIN=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/bin
CMD=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/cmd
LIB=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
