#!/bin/sh

# Set these paths appropriately

BIN=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/bin
CMD=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/cmd
LIB=/Users/michele/Dropbox/Workspace/ManTIME/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
